name: Prettier

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check formatting
        run: npm run format:check
        
      # Optional: Automatically fix and commit formatting issues
      - name: Fix formatting
        if: failure()
        run: |
          npm run format
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git commit -m "style: format with prettier"
          git push
